variable "access_key" {}
variable "secret_key" {}
variable "region" {}
variable "ami" {}
variable "key_name" {}
variable "key_path" {}
variable "instance_type" {}
variable "tag_name" {}
variable "vpc_cidr" {}
variable "db_password" {}
variable "cert_body" {}
variable "cert_private_key" {}
variable "cert_chain" {}
variable "db_username" {}
variable "db_name" {}
variable "availability_zones" {}
variable "asg_min" {}
variable "asg_max" {}
variable "asg_desired" {}
variable "subnets" {}
variable "domain" {}
